name: Reusable Semgrep Scan

on:
  workflow_call:

jobs:
  semgrep_scan:
    name: Security Scan (Semgrep)
    runs-on: ubuntu-latest
    
    # O Semgrep oficial roda em um container Docker muito mais seguro e rápido
    container:
      image: semgrep/semgrep

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep Scan
        run: |
          # 1. Instala o Semgrep permitindo pacotes do sistema
          pip install semgrep --break-system-packages
          
          # 2. Executa usando os pacotes oficiais diretamente (sem precisar de curl)
          # Isso puxa as regras de segurança oficiais de Python diretamente da nuvem deles
          semgrep --config p/python --config p/security .
