name: Reusable OWASP ZAP Scan

on:
  workflow_call:
    inputs:
      target_url:
        required: true
        type: string
        description: 'A URL do site/aplicação que será testada'
  
  workflow_dispatch:
    inputs:
      target_url:
        description: 'URL para testar manualmente'
        required: true
        default: 'https://www.zaproxy.org'

  push:
    paths:
      - '.github/workflows/zap-scan.yml'

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Run OWASP ZAP Baseline Scan
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Criamos a pasta .zap e um arquivo de regras vazio caso ele não exista,
      # evitando o erro de "rules file not found" que apareceu no seu log.
      - name: Create default rules directory if missing
        run: |
          mkdir -p .zap
          touch .zap/rules.tsv

      - name: Run ZAP Baseline Scan via Docker
        run: |
         docker run --user root -v ${{ github.workspace }}:/zap/wrk/:rw --network=host -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
          -t ${{ github.event.inputs.target_url || inputs.target_url || 'https://www.zaproxy.org' }} \
          -c .zap/rules.tsv \
          -J report_json.json \
          -w report_md.md \
          -r report_html.html || true
  
      - name: Upload ZAP Scan Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-results
          path: |
            report_html.html
            report_md.md
            report_json.json
